
awkward:
	../l/make/170508_mkhtml.sh \
        2008/awkward/awkward_gestures.mdsh 2008/awkward/index.html \
	../l/make/160209_html.functions ../l/make/160426_html.functions	
codebrut:
	../l/make/170508_mkhtml.sh \
        2004/codebrut/here.mdsh 2004/codebrut/index.html \
	../l/make/160209_html.functions ../l/make/160426_html.functions
