
btsw:
	../l/make/160421_mkhtml.sh 2016/btsw/here.mdsh \
	2016/btsw/index.html

info:
	../l/make/160421_mkhtml.sh \
	about/here.mdsh about/index.html \
	../l/make/160209_html.functions ../l/make/160426_html.functions	

com:
	../l/make/160421_mkhtml.sh commission/here.mdsh \
	commission/index.html



awkward:
	../l/make/160421_mkhtml.sh \
        2008/awkward/awkward_gestures.mdsh 2008/awkward/index.html \
	../l/make/160209_html.functions ../l/make/160426_html.functions	
sabocu:
	../l/make/160421_mkhtml.sh \
        2013/sabocu/sandbox_culture.mdsh 2013/sabocu/index.html \
	../l/make/160209_html.functions ../l/make/160426_html.functions	
wasted:
	../l/make/160421_mkhtml.sh \
        2016/wasted/here.mdsh 2016/wasted/index.html \
	../l/make/160209_html.functions ../l/make/160426_html.functions	
london:
	../l/make/160421_mkhtml.sh \
        2016/london/here.mdsh 2016/london/index.html \
	../l/make/160209_html.functions ../l/make/160426_html.functions	
hilxalsh:
	../l/make/160421_mkhtml.sh \
        2016/hilxalsh/here.mdsh 2016/hilxalsh/index.html \
	../l/make/160209_html.functions ../l/make/160426_html.functions	
dry:
	../l/make/160421_mkhtml.sh \
        2014/dry/here.mdsh 2014/dry/index.html \
	../l/make/160209_html.functions ../l/make/160426_html.functions	
hcatfowysiwyg:
	../l/make/160421_mkhtml.sh \
        2014/hcatfowysiwyg/here.mdsh 2014/hcatfowysiwyg/index.html \
	../l/make/160209_html.functions ../l/make/160426_html.functions	
manpages:
	../l/make/160421_mkhtml.sh \
        2016/manpages/here.mdsh 2016/manpages/index.html \
	../l/make/160209_html.functions ../l/make/160426_html.functions	
blindtext:
	../l/make/160421_mkhtml.sh \
        2016/blindtext/here.mdsh 2016/blindtext/index.html \
	../l/make/160209_html.functions ../l/make/160426_html.functions	

demo:
	../l/make/160421_mkhtml.sh \
        2016/demo/here.mdsh 2016/demo/index.html \
	../l/make/160209_html.functions ../l/make/160426_html.functions	

makehrefs:
	../l/make/160421_mkhtml.sh \
        2016/makemdsh/makehrefs/here.mdsh 2016/makemdsh/makehrefs/index.html \
	../l/make/160209_html.functions ../l/make/160426_html.functions	
codebrut:
	../l/make/160421_mkhtml.sh \
        2004/codebrut/code_brut.mdsh 2004/codebrut/index.html \
	../l/make/160209_html.functions ../l/make/160426_html.functions	

mdshdok:
	../l/make/160421_mkhtml.sh \
        2015/mdsh/here.mdsh 2015/mdsh/index.html \
	../l/make/160209_html.functions ../l/make/160426_html.functions	

petter:
	../l/make/160421_mkhtml.sh \
        2014/petter/here.mdsh 2014/petter/index.html \
	../l/make/160209_html.functions ../l/make/160426_html.functions	

fritzing:
	../l/make/160421_mkhtml.sh \
        2016/fritzing/here.mdsh 2016/fritzing/index.html \
	../l/make/160209_html.functions ../l/make/160426_html.functions	

